parser: babel-eslint
env:
  es6: true
  node: true
extends: airbnb
parserOptions:
  sourceType: module
rules:
  indent:
    - 2
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
